### ISSUE TITLE
CAN: All Testimonial page - Cards title+description on same line, not spaced

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-portal#405] opened 2020-10-28 20:05 UTC
![image](https://user-images.githubusercontent.com/60662056/97490418-35b6cc00-1937-11eb-9840-b836c3c9f25a.png)
New testimonial on All Testimonials page - title and description are not on different lines - 
THEYARERIGHTinline with no space

**Comment by BradHN1** [comment] 2020-10-29 15:37
Duplicate of issue #386

**Closed by BradHN1** 2020-10-29 15:37 UTC
Labels: duplicate
