### ISSUE TITLE
Phone - user profile display does not show impact without scrolling right

### ISSUE THREAD

**Issue by ellentohn** [massenergize/frontend-portal#151] opened 2020-03-27 16:39 UTC
On iphone 6, when I go to my profile  I can see the first 2 boxes, 
- actions completed
- actions to do
I see only the beginning outline of the third box "impact (in lbs CO2) -- the user does not know to scroll right. Is there a way to make the boxes smaller so that all 3 fit in one view or what are our other options for display. 

@kaatvds how does this look on your phone?
![Phone user profile impact cut off iphone](https://user-images.githubusercontent.com/60329553/77778778-ec607000-7027-11ea-900b-5d73663f87f4.png)

**Comment by kaatvds** [comment] 2020-04-03 14:54
duplicate of #162 - closing and removing from board

**Closed by kaatvds** 2020-04-03 14:54 UTC
Labels: priority 2
